AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - "db/schema*.rb"
  TargetRubyVersion: 3.3
  SuggestExtensions: false
